[package]
org = "gabilan"
name = "ticket_booking"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "mysql-connector-java"
version = "8.0.18"
path = "./mysql-connector-java-8.0.18.jar"
groupId = "mysql"